version: '3'
services:
    nginx:
        build: .
        image: portfolio
        container_name: portfolio
        restart: always
        ports:
            - 9999:80
        volumes:
            - .:/usr/share/nginx/html
